### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by svg153** [pxp9/WeatherBot#1]
Hi 👋.

Very cool.

Some suggestions:
- Create a `README.md`: describing the bot, which is needed to run it, and explaining the bot's commands and so on.
- Put the label of the license you have chosen in the `README.md`.
- Delete the pycache folder and ignore it by putting it in the `.gitignore` file.

As a suggestion to learn, try to dockerize the bot.

Keep it up!.

**Comment by pxp9** [comment]
Done i will dockerize the bot when i finish the proyect
